name: actions

on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: main
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
      run: |
        python ./main.py

    - name: Commit changes
      run: |
        git config user.email "erkanncelen@gmail.com"
        git config user.name "Erkan Celen"
        git add ./docs
        git commit -m "Updating the index html in docs dir for Github pages"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
